package network;

public enum MessageType {
    MAX_PLAYERS_FOR_GAME,
    USER_INFO,
    PICK_OBJECT,
    PUT_OBJECT,
    GENERIC_ERROR,
    SHOW_LIBRARY,
    SHOW_BOARD,
    SHOW_PERSONAL_OBJECTIVE,
    SHOW_COMMON_OBJECTIVE,
    SHOW_OBJECTS_IN_HAND
}
